name: Testing Haystack-Readme integration

on:
  push:
    branches:
      - sync-nodes-doc-test

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Github Action
        uses: readmeio/rdme@7.2.0
        with:
          rdme: docs ./docs --key=4ShCDfmKYSGB7GyabeR3Z0S2mSKOwvUT --version=2.0
